// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: drivers/driver_input.proto

package drivers

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	generic "ksuser/pb/generic"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DriverListInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids            []string            `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Names          []string            `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Phones         []string            `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	LicenceNumbers []string            `protobuf:"bytes,4,rep,name=licence_numbers,json=licenceNumbers,proto3" json:"licence_numbers,omitempty"`
	CompanyIds     []string            `protobuf:"bytes,5,rep,name=company_ids,json=companyIds,proto3" json:"company_ids,omitempty"`
	Pagination     *generic.Pagination `protobuf:"bytes,6,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *DriverListInput) Reset() {
	*x = DriverListInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drivers_driver_input_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverListInput) ProtoMessage() {}

func (x *DriverListInput) ProtoReflect() protoreflect.Message {
	mi := &file_drivers_driver_input_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverListInput.ProtoReflect.Descriptor instead.
func (*DriverListInput) Descriptor() ([]byte, []int) {
	return file_drivers_driver_input_proto_rawDescGZIP(), []int{0}
}

func (x *DriverListInput) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DriverListInput) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *DriverListInput) GetPhones() []string {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *DriverListInput) GetLicenceNumbers() []string {
	if x != nil {
		return x.LicenceNumbers
	}
	return nil
}

func (x *DriverListInput) GetCompanyIds() []string {
	if x != nil {
		return x.CompanyIds
	}
	return nil
}

func (x *DriverListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_drivers_driver_input_proto protoreflect.FileDescriptor

var file_drivers_driver_input_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x73,
	0x75, 0x73, 0x65, 0x72, 0x1a, 0x1d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x0f, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x69, 0x63, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64,
	0x73, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x73, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1b, 0x5a, 0x19, 0x6b, 0x73, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x70, 0x62, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x3b, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drivers_driver_input_proto_rawDescOnce sync.Once
	file_drivers_driver_input_proto_rawDescData = file_drivers_driver_input_proto_rawDesc
)

func file_drivers_driver_input_proto_rawDescGZIP() []byte {
	file_drivers_driver_input_proto_rawDescOnce.Do(func() {
		file_drivers_driver_input_proto_rawDescData = protoimpl.X.CompressGZIP(file_drivers_driver_input_proto_rawDescData)
	})
	return file_drivers_driver_input_proto_rawDescData
}

var file_drivers_driver_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_drivers_driver_input_proto_goTypes = []interface{}{
	(*DriverListInput)(nil),    // 0: ksuser.DriverListInput
	(*generic.Pagination)(nil), // 1: ksuser.Pagination
}
var file_drivers_driver_input_proto_depIdxs = []int32{
	1, // 0: ksuser.DriverListInput.pagination:type_name -> ksuser.Pagination
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drivers_driver_input_proto_init() }
func file_drivers_driver_input_proto_init() {
	if File_drivers_driver_input_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drivers_driver_input_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverListInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drivers_driver_input_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drivers_driver_input_proto_goTypes,
		DependencyIndexes: file_drivers_driver_input_proto_depIdxs,
		MessageInfos:      file_drivers_driver_input_proto_msgTypes,
	}.Build()
	File_drivers_driver_input_proto = out.File
	file_drivers_driver_input_proto_rawDesc = nil
	file_drivers_driver_input_proto_goTypes = nil
	file_drivers_driver_input_proto_depIdxs = nil
}
